baconpaul/airwin2rack

src/Module.cpp

1. Help widget handles zoom-while-open better and closes if the browser toggles open
2. json_object_set leaks apparently! Switch to _new.

Two pre-release fixes; Zoom Help and Leak Json

---

src/Module.cpp

1. Add a "Panic Reset" menu item which resets the effect to blank
2. Add input and output attenuators
Addresses #16

Panic Menu Item; Input and Output Attenuators

---

src-juce/AWConsolidatedEditor.cpp
src-juce/AWConsolidatedEditor.h
src-juce/AWConsolidatedProcessor.cpp
src-juce/AWConsolidatedProcessor.h
src/AirwinRegistry.cpp
src/AirwinRegistry.h

1. Menus can be in Chris order in JUCE
2. Juce gets a properties bundle
3. clang-format the code

Chris order menus; clang-format

---

.github/workflows/build-daw-plugin.yml
src-juce/AWConsolidatedEditor.cpp
src-juce/AWConsolidatedEditor.h

From meny and from the bottom strip

Add links to airwindows.com

---

src-juce/AWConsolidatedEditor.cpp
src-juce/AWConsolidatedProcessor.cpp
src-juce/AWConsolidatedProcessor.h

- Edit gestures
- Better spoken names and invalidation
- Actually not that bad!

Accessibility Set 2

---

src-juce/AWConsolidatedEditor.cpp

Pretty cool actually!
Need to do accesibility ....

JUCE side typein editor works

---

CMakeLists.txt
src-juce/AWConsolidatedEditor.cpp
src-juce/AWConsolidatedEditor.h
src-juce/CMakeLists.txt

Needs a fix before merging.
Currently some changes are not happening until relaunch (when switching system theme), not sure why. The worst one is the documentation text color.
Added an enum to map colors. There are 2 methods using setColour to adjust the theme, and the JUCE dark mode listener to set initial theme and respond to system changes for now. Colours are set using findColour.

Add light theme and listen for system theme changes

---

src-juce/AWConsolidatedEditor.cpp

A simple bool on our timer meant if a jog hold fired while the subsequent mouse was down you would get a double bump. A simple 'jogging or not' is not enough but a click counter does the trick, so move to that.
Closes #62

Fix jog-hold misfire in jog effect selectors

---

src-juce/AWConsolidatedEditor.cpp

juce::PropertiesFile::Options::getDefaultFile makes a bad choice on linux of just dumping into home dir, so if JUCE_LINUX is true set the properties file directory to ".config/AirwindowsConsolidated" which works.
Closes #72

Fix the Linux settings location

---

src-juce/AWConsolidatedProcessor.cpp
src-juce/AWConsolidatedProcessor.h

Use the display processor copy for more things in the UI and the audio thread one for less. This means that problems with not switching whtn the UI thread is in various uncalled states are all fixed, it seems.

Modify our UI display vs Processor strategy

---

src-juce/AWConsolidatedEditor.cpp
src-juce/AWConsolidatedProcessor.cpp
src-juce/AWConsolidatedProcessor.h

https://forum.renoise.com/t/macos-crash-with-airwindows-vst-when-changing-presets/72288/9
Renoise re-enters get during set notifying, and no other daw does, but that deadlocked me. So move my sets outside my setup.
Closes #87

Work around a Renoise Re-Entrant Param Difference

---

src-juce/AWConsolidatedEditor.cpp
src-juce/AWConsolidatedEditor.h
src-juce/AWConsolidatedProcessor.cpp
src-juce/AWConsolidatedProcessor.h

- The default startup property is Galactic. Allow users to overdide this as a sticky preference. Closes #93
- While at it, fix the macos preferences file location.

Startup Effect Property; Move Properties on macOS

---

src-juce/AWConsolidatedProcessor.cpp
src-juce/AWConsolidatedProcessor.h

The 'text-for' display processor used the current values but not the handed ones. Duh! This will fix a few random bugs we've heard about I'm sure, but definitely fixes #94

When doing 'text-for' make sure to use the value

---

src-juce/AWConsolidatedEditor.cpp

Tab traverser happily walked into an invisible component if it was accessible, which with doc hidden we sort of have.
So don't do that.
Closes #128

Have tab traversal work with doc off

---

CMakeLists.txt
src-juce/AWConsolidatedProcessor.cpp
src-juce/CMakeLists.txt

This PR fixes the usage of MACRO `USE_JUCE_PROGRAMS` to use juce program to change effect. Details as follows :
- Do not return early. Instead return correct values as per the value of `USE_JUCE_PROGRAMS` in `AWConsolidatedAudioProcessor::getProgramName`, `AWConsolidatedAudioProcessor::getCurrentProgram`, `AWConsolidatedAudioProcessor::getNumPrograms`
- Add a cmake option to allow setting `USE_JUCE_PROGRAMS` to compile definitions

Fixes to make USE_JUCE_PROGRAMS macro actually use juce programs

---

src-juce/AWConsolidatedEditor.cpp
src-juce/AWConsolidatedEditor.h

- Looks for documentation file \<settingsDir\>/customDocs/\<plugin-name\>.txt
- If custom documentation exists, it is prepended to the standard documentation with a separator.
- The last loaded custom documentation is cached to avoid repeated file reads on calls to resizeDocArea()
(settingsDir is the same dir where favorites are stored)
Code changes:
- Added loadCustomDocumentation() to handle reading and caching documentation.
- Updated resizeDocArea() to include custom documentation if available.
- Move directory stuff from getFavoritesFile(), into its own getSettingsDirectory(), for reuse in loadCustomDocumentation()

Loading of custom docs from txt files

---

src-juce/AWConsolidatedEditor.cpp

If the favorites file didn't parse I tried to read the parse result anyway, leading to a crash on startup

Handle a crash case with corrupted favorites file

---

.github/workflows/build-daw-plugin.yml

Try a docker build

---

src-juce/AWConsolidatedProcessor.cpp
src-juce/AWConsolidatedProcessor.h

Eliminated the need for temporary audio buffers in AWConsolidatedAudioProcessor by utilizing the applyGain() method in juce::AudioBuffer.
It automatically applies the gain to all buffers, simplifying the buffer handling when M->M might be supported.
It also neatly solves a FIXME regarding hardcoded buffer lengths.
If anything needs change just let me know :-)

Use juce::AudioBuffer::applyGain to simplify buffer handling

---

src-juce/AWConsolidatedProcessor.cpp

Otherwise the input gain is only applied to the left channel. 
This fixes #197

Make sure input gain is applied to buffer before taking copy for the mono input mode.
