baconpaul/airwin2rack

src/Module.cpp
An option. This refactors so mono is a branch and poly also allocates properly. And it all works!
=> Polyphonic or Monophonic FX

src/Module.cpp
Still have the block size crash
=> Fix Windows Help Crash

res/port_off.svg, res/port_off_light.svg, res/port_on.svg, res/port_on_light.svg, src/Module.cpp
The port stays visible but goes gray when not in use with custom port graphics (borrowed from surge for now).
=> Custom Port with On/Off state

src/Module.cpp
Which, honestly, is kinda cool.
=> Add typeahead search to the Airwindows selector

scripts/configure.pl, src/AirwinRegistry.cpp, src/AirwinRegistry.h, src/Module.cpp, src/ModuleAdd.h
Chris ordering is the airwindowspedia ordering and is a view of quality rather than just alpha by name. If you don't know that it looks a bit like a menu osrting but so keep it off by default but make it a collection-wide option.
=> "Chris" ordering

scripts/import.pl, src/Module.cpp, src/ModuleAdd.h, src/autogen_airwin/Channel5.cpp, src/autogen_airwin/Channel6.cpp, src/autogen_airwin/Channel7.cpp, src/autogen_airwin/Channel8.cpp
1. Upgrade airwindows
2. A few more unstream tweaks ready for release
3. Handle the Chanel typeins with "output"
This is the candidate for the 2.0.0 release.
=> Upgrade Airwindows; Ready for Release

src/Module.cpp
MixMaster uses a 1-8 LRLRLRLRLRLR and 9-16 LRLRLRLRLR as opposed to an LLLLL RRRRRR topology for its inserts, so make the module handle either topology as a different polyphony mode.
=> Add a second Poly mode for MixMaster insert

src/Module.cpp
standard and poly but then 4 mixmasters. Phew!
=> Add all the variations of mixmaster summing

src/Module.cpp
Implement the sst::rackhelpers::module_connnector::NeibhtorCoonectable_V1 api, meaning this now participates in mixmaster and surge interconnect mouse actions.
=> Wont you be my neighbor?

.github/workflows/build-daw-plugin.yml, CMakeLists.txt, Makefile, README.md, cmake/CPM.cmake, cmake/CmakeRC.cmake, cmake/basic-installer.cmake, res/LICENSE.gpl3, res/installer_mac/License.txt, res/installer_mac/Readme.rtf, scripts/installer_mac/make_installer.sh, src-juce/AWConsolidatedEditor.cpp, src-juce/AWConsolidatedEditor.h, src-juce/AWConsolidatedProcessor.cpp, src-juce/AWConsolidatedProcessor.h, src-juce/CMakeLists.txt, src/AirwinRegistry.h, src/Module.cpp, src/airwin2rackbase.cpp, src/airwin2rackbase.h
With optional build etc... and a full JUCE plugin and a library version.
=> Add a Consolidated JUCE plugin side by side with Rack

.github/workflows/build-daw-plugin.yml
and have PR be less build and debug to be quicker
=> Segregate pull request from release run

CMakeLists.txt, src-juce/AWConsolidatedEditor.cpp, src/AirwinRegistry.cpp, src/AirwinRegistry.h
so not everyone has to roll their own
adjust the juce module
leave the rack module as is
=> Include the documentation in the libarry

src-juce/AWConsolidatedEditor.cpp
Add a no-params label for the no params case
=> Hide knobs and displays for inactive

src-juce/AWConsolidatedEditor.cpp
Ready for ally but also adds some sparkle
Also up the font sizes in the doc
=> Hover gestures on components; Separate componetns in picker

src-juce/AWConsolidatedEditor.cpp, src-juce/AWConsolidatedEditor.h
- Tab order
- Names on things starting to be ther
- Read the doc
Still
- No edit
- No typein control
=> Accessibility, Part one

src-juce/AWConsolidatedEditor.cpp, src-juce/AWConsolidatedEditor.h, src-juce/AWConsolidatedProcessor.cpp
- The Editable UI is togglable either by menu or F7
- Initialization should now work with doc area sized etc
=> More accesibility fixes

src-juce/AWConsolidatedEditor.cpp, src-juce/AWConsolidatedEditor.h, src/AirwinRegistry.cpp, src/AirwinRegistry.h
=> More efficient data structures for collections

src-juce/AWConsolidatedProcessor.cpp
Sure. Why not. Bet the zynthian folks will like it at least.
=> Expose the library as built in presets to the DAW

src-rack/Module.cpp
- Store collection as a variable on skin and write to config
- Collection support done in the menu, jog and search
=> Rack gets collection aware menus and jogs

scripts/import.pl, src/autogen_airwin/Balanced.cpp, src/autogen_airwin/Channel4.cpp, src/autogen_airwin/Channel5.cpp, src/autogen_airwin/Channel6.cpp, src/autogen_airwin/Channel7.cpp, src/autogen_airwin/Channel8.cpp, src/autogen_airwin/Channel9.cpp, src/autogen_airwin/ClearCoat.cpp, src/autogen_airwin/CloudCoat.cpp, src/autogen_airwin/DitherFloat.cpp, src/autogen_airwin/Fracture2.cpp, src/autogen_airwin/NodeDither.cpp, src/autogen_airwin/SampleDelay.cpp
Still not all the way there, but lots better
=> Improve the coverage of int typeins

src-juce/AWConsolidatedEditor.cpp
Add mouse wheel support to parameters
Tested on logitech mouse with windows 11 and trackpad with MBP
=> MouseWheel Support

src-juce/AWConsolidatedEditor.cpp
HighImpact is missing. Chris will fix in the 'pedia for his next push but I might as well recover a bit better.
Closes #102
=> Show what.txt if airwindowspedia is missing

src-juce/AWConsolidatedEditor.cpp, src-juce/AWConsolidatedProcessor.cpp, src/AirwinRegistry.h
from DefaultLookAndFeel vs LocalLookAndFeel
=> Fix the 'Paint it Black' problem

src-juce/AWConsolidatedProcessor.cpp
Live 11, on device duplication, ignored the update host display but ignored it in a sticky way. Hit it with a hammer a couple of times to make sure it's actually turned on.
Addresses #112
=> Work around an aparent cache bug in Live 11

src-juce/AWConsolidatedEditor.cpp, src-juce/AWConsolidatedEditor.h
now jog and menu return to jog and menu when triggered
=> Fix an accesibility tab order focus issue

src-juce/AWConsolidatedEditor.cpp, src-juce/AWConsolidatedEditor.h
=> Click on the category name for a category only menu

src-juce/AWConsolidatedEditor.cpp, src-juce/AWConsolidatedEditor.h, src-juce/AWConsolidatedProcessor.cpp, src-juce/AWConsolidatedProcessor.h
Level from -inf to +18db
Knobs and automatable
Closes #85
=> Add an input and output gain parameter

src-juce/AWConsolidatedProcessor.cpp, src-juce/AWConsolidatedProcessor.h
1. Consolidate some of the code into the param
2. If the param is at 0db don't touch the signal at all
3. Fix a -0.00db display which arose
=> Tweak the amplitude stage a bit

src/AirwinRegistry.cpp, src/AirwinRegistry.h
If you are in "Chris" order and in the juce plugin you now have jogs consistent with menu.
Closes #152
=> Jog buttons obey "Chris" order in JUCE plugin

src-juce/AWConsolidatedEditor.cpp
=> show config dir, moved to settings menu

src-juce/AWConsolidatedEditor.cpp
=> This time *really* do jog with chris order
